spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  sql:
    init:
      schema-locations: classpath*:schema.sql
      data-locations: classpath*:data.sql
      mode: always

mybatis:
  mapper-locations: mapper/*.xml